spring:
  application:
    name: first-microservice    
  config:
    import: optional:configserver:http://localhost:8888  
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/